const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
(async()=>{
  const nodes={},elements=[],windowEvents={};
  class Element {
    constructor(tag='div'){this.tag=tag;this.children=[];this.events={};this.attributes={};this.dataset={};this.value='';this.textContent='';this.className='';this.classList={add(){},remove(){}};elements.push(this);}
    set id(value){this._id=value;nodes[value]=this;} get id(){return this._id;}
    append(...n){for(const child of n)child.parentElement=this;this.children.push(...n);} prepend(...n){for(const child of n)child.parentElement=this;this.children.unshift(...n);}
    replaceChild(next,previous){this.children[this.children.indexOf(previous)]=next;next.parentElement=this;previous.parentElement=null;}
    replaceChildren(...n){this.children=[...n];} addEventListener(k,f){this.events[k]=f;}
    setAttribute(k,v){this.attributes[k]=v;} focus(){this.focused=true;}
    blur(){this.events.change?.();}
    closest(){return null;}
    querySelector(selector){return selector.startsWith("#")?nodes[selector.slice(1)]||null:null;}
    replaceWith(next){this.parentElement.replaceChild(next,this);}
    querySelectorAll(){const found=[];const visit=node=>{for(const child of node.children){if(['input','select','textarea','button','summary'].includes(child.tag))found.push(child);visit(child);}};visit(this);return found;}

    showModal(){this.open=true;} close(){this.open=false;} click(){return this.events.click?.({preventDefault(){}});}
  }
  const main=new Element(),settings=new Element(),body=new Element(),calls=[],saved=new Map();
  const settingsHeading=new Element("h2");settingsHeading.id="workspaceSettingsTitle";settings.append(settingsHeading);
  let accept=true,legacyKbh=false,persistedDock=[];
  const ctx=vm.createContext({document:{body,createElement:tag=>new Element(tag),getElementById:id=>nodes[id]||null,
    querySelector:q=>q==='main.layout'?main:settings},window:{addEventListener(name,handler){windowEvents[name]=handler;}},console,
    Event:class {constructor(type){this.type=type;}},currentLang:'de',appConfig:{active_device_id:'master'},managementDeviceUrl:()=> 'http://device',
    confirm:()=>accept,prompt:()=>null,TextEncoder,btoa:s=>Buffer.from(s,'binary').toString('base64'),URLSearchParams,
    api:async(url,options)=>{calls.push({url,...options});const action=url.split('/').at(-1);
      if(action==='dock-load')return {dock:JSON.parse(JSON.stringify(persistedDock))};
      if(action==='dock-save'){persistedDock=JSON.parse(JSON.stringify(options.body.dock));return {dock:persistedDock};}
      if(action==='settings')return {brewfather_user:'User',key_saved:true,import_options:{boil_temp:98}};
      if(action==='save'){
        const value=JSON.parse(JSON.stringify(options.body.draft));value.group_id=value.group_id||value.id;value.version=value.version||1;
        if(options.body.new_version){value.id='new-version-id';value.version++;}
        saved.set(value.id,value);return value;
      }
      if(action==='list')return [...saved.values()];
      if(action==='load')return JSON.parse(JSON.stringify(saved.get(options.body.id)));
      if(action==='delete'){saved.delete(options.body.id);return {deleted:options.body.id};}
      if(action==='export')return {misc:[{File:'/Rezepte/test.json'}],mash:[]};
      if(action==='snapshot-load')return null;
      if(action==='bf-list')return options.body.kind==='recipes'?[{_id:'r2',name:'Zebra',author:'Anna',style:{name:'Porter'},_timestamp_ms:Date.parse('2026-01-10T12:00:00Z'),_created:{_seconds:Date.parse('2025-12-01T12:00:00Z')/1000}},{_id:'r1',name:'Amber',author:'Zoe',style:{name:'IPA'},_timestamp:{_seconds:Date.parse('2026-02-01T12:00:00Z')/1000},createdAt:'2025-01-10T12:00:00Z'},{_id:'r3',name:'Missing'}]:[{_id:'b1',name:'Sud',batchNo:7,recipe:{name:'Amber'}}];
      if(action==='kbh-list'&&legacyKbh)return [{id:1,name:'Legacy batch'}];
      if(action==='kbh-list')return [0,1,2,3].map(status=>({id:status+1,name:'Batch '+status,status,number:status+10,brewed_at:'2026-09-28',saved_at:'2026-09-29',watchlist_id:status===1?7:0}));
      if(url.startsWith('/api/explorer/list?')){
        const query=new URLSearchParams(url.split('?')[1]);assert.equal(query.get('side'),'local');assert.equal(query.has('base_url'),false);
        return {files:query.get('path')==='/'?[{name:'Rezepte',type:'dir',path:'/Rezepte'}]:query.get('path')==='/Rezepte'?[{name:'Archiv',type:'dir',path:'/Rezepte/Archiv'}]:[{name:'Plan.json',type:'file',path:'/Rezepte/Archiv/Plan.json'},{name:'Plan_1.json',type:'file',path:'/Rezepte/Archiv/Plan_1.json'}]};
      }
      if(url.startsWith('/api/explorer/preview?'))return {text:'{"misc":[{"Sudname":"Inventory"}],"mash":[]}'};
      if(action==='inventory-load')return {schema:1,id:'12345678901234567890123456789012',name:'Inventory',generation:'1.67+',steps:[],dock:[],misc:{},notices:[]};
      if(action==='inventory-publish')return {...options.body.draft,id:'published',inventory_ref:{id:'inventory-id'}};
      if(action==='import')return {schema:1,id:'12345678901234567890123456789012',name:options.body.recipe.misc[0].Sudname,generation:'1.67+',steps:[],dock:[],misc:{},notices:[]};
      return {done:true};}
  });
  vm.runInContext(fs.readFileSync('static/app.js','utf8').match(/function versionInfoForName[\s\S]*?\n}/)[0],ctx);
  vm.runInContext(fs.readFileSync('static/explorer.js','utf8'),ctx);
  vm.runInContext(fs.readFileSync('static/designer-core.js','utf8'),ctx);
  vm.runInContext(fs.readFileSync('static/designer.js','utf8'),ctx);
  vm.runInContext('initializeDesigner()',ctx);await Promise.resolve();
  assert.ok(nodes.designerPanel);assert.equal(nodes.designerBfKey.type,'password');assert.equal(nodes.designerBfKey.value,'');
  assert.equal(nodes.designerBoilTemp.value,98);
  vm.runInContext('pdInsert({label:"Rast",temp:63,duration:30})',ctx);
  assert.equal(nodes.designerSteps.children.length,1);
  const first=vm.runInContext('pd.draft.steps[0].id',ctx);
  const transfer=new Map();nodes.designerSteps.children[0].events.dragstart({dataTransfer:{setData:(k,v)=>transfer.set(k,v)}});
  nodes.designerDock.events.drop({preventDefault(){},stopPropagation(){},dataTransfer:{getData:k=>transfer.get(k)}});
  assert.equal(nodes.designerDock.children.length,1);assert.equal(nodes.designerSteps.children.length,0);
  vm.runInContext('pdHistory("undo","redo")',ctx);assert.equal(nodes.designerSteps.children.length,1);
  vm.runInContext('pdHistory("redo","undo")',ctx);assert.equal(nodes.designerDock.children.length,1);
  nodes.designerName.value='Saved';nodes.designerName.events.change();await vm.runInContext('pdSave()',ctx);
  assert.equal([...saved.values()][0].dock[0].id,first);
  assert.equal(vm.runInContext('pd.dirty',ctx),false);
  await vm.runInContext('pd.draft.snapshot={actors:[{NAME:"Pump"}],kettles:[],profiles:{},captured_at:1}; pdAccept(PlanDesigner.create())',ctx);
  assert.equal(vm.runInContext('pd.draft.snapshot.actors[0].NAME',ctx),'Pump');
  vm.runInContext('pdInsert({label:"Keep"})',ctx);accept=false;
  const cancelled=vm.runInContext('pdAccept(PlanDesigner.create())',ctx);
  nodes.designerUnsavedDialog.children[4].children[2].click();
  assert.equal(await cancelled,false);
  assert.equal(vm.runInContext('pd.draft.steps[0].Rast',ctx),'Keep');
  vm.runInContext('pdReview()',ctx);assert.equal(nodes.designerDialog.open,true);
  assert.ok(nodes.designerDialog.children[1].children.length>0);
  vm.runInContext("pd.draft.name='Transfer test'",ctx);
  const transferBefore=vm.runInContext('JSON.stringify(pd.draft)',ctx);
  await nodes.designerTransfer.click();
  const upload=calls.find(c=>c.url==='/api/explorer/action');
  assert.equal(upload.body.path,'/Rezepte/test.json');assert.equal(upload.body.action,'upload');
  assert.equal(upload.body.designer_context.profile,'master');
  assert.equal(nodes.designerDialog.open,true);
  assert.match(nodes.designerDialog.children[1].children[0].textContent,/erfolgreich übertragen.*Rezepte/);
  assert.match(nodes.designerStatus.textContent,/erfolgreich übertragen/);
  assert.ok(calls.some(call=>call.url==='/api/designer/export'));
  const apiBeforeFailure=ctx.api;
  ctx.api=async(url,options)=>{if(url==='/api/explorer/action')throw new Error('Test upload failed');return apiBeforeFailure(url,options);};
  await nodes.designerTransfer.click();
  assert.match(nodes.designerDialog.children[1].children[0].textContent,/Übertragung fehlgeschlagen: Test upload failed/);
  assert.equal(nodes.designerDialog.children[1].children[0].attributes.role,'alert');
  assert.match(nodes.designerStatus.textContent,/Übertragung fehlgeschlagen/);
  ctx.api=apiBeforeFailure;

  assert.deepEqual(JSON.parse(Buffer.from(upload.body.content,'base64').toString()),{misc:[{File:'/Rezepte/test.json'}],mash:[]});
  assert.equal(vm.runInContext('JSON.stringify(pd.draft)',ctx),transferBefore);
  assert.ok(!calls.some(c=>/reboot|play|start/.test(c.url)));
  assert.equal(nodes.designerTransfer.title,'Maischeplan auf Gerät übertragen');
  assert.ok(!elements.some(e=>e.title==='Maischeplan importieren'));
  assert.ok(!elements.some(e=>e.title==='Auf Gerät übertragen'));
  accept=true;
  vm.runInContext('pd.dirty=false',ctx);
  await vm.runInContext('pdInventoryPlans()',ctx);
  const inventoryPicker=nodes.designerDialog.children[1];
  assert.ok(!inventoryPicker.children.some(n=>n.tag==='input'));
  assert.equal(inventoryPicker.children.length,1); // no breadcrumb or mkdir toolbar
  const inventoryTable=inventoryPicker.children[0].children[0],inventoryList=inventoryTable.children[1];
  assert.equal(inventoryList.children[0].children[0].children[0].children[1].textContent,'Archiv');
  const inventoryName=inventoryTable.children[0].children[0].children[0];
  assert.equal(inventoryName.attributes['aria-sort'],'ascending');
  inventoryName.children[0].click();assert.equal(inventoryName.attributes['aria-sort'],'descending');
  assert.equal(inventoryName.children[0].children[0].textContent,'▾');
  await inventoryList.children[0].children[0].children[0].click();
  assert.equal(inventoryList.children[0].children[0].children[0].children[0].textContent,'..');
  await inventoryList.children[0].children[0].children[0].click();
  assert.equal(inventoryList.children.length,1); // navigation stops at /Rezepte
  await inventoryList.children[0].children[0].children[0].click();
  assert.equal(inventoryList.children.length,2);
  const parent=inventoryList.children[1];
  assert.equal(parent.className,'version-group');
  parent.children[0].children[0].click();
  assert.equal(inventoryList.children.length,4);
  const latest=inventoryList.children[2],child=inventoryList.children[3];
  assert.equal(latest.children[0].children[0].textContent,'Version 2 · Neueste');
  assert.equal(child.className,'explorer-version-row');
  assert.equal(child.children[0].children[0].textContent,'Version 1');
  await child.children[0].children[0].click();

  assert.equal(vm.runInContext('pd.draft.name',ctx),'Inventory');
  assert.equal(vm.runInContext('pd.dirty',ctx),false);
  assert.equal(nodes.designerDialog.open,false);
  vm.runInContext("pd.draft.snapshot={actors:[{NAME:'Ruehrwerk',PWMSW:true}],kettles:[],profiles:{}};pd.draft.steps=[PlanDesigner.step('Ruehrwerk:OFF')];pd.selected=pd.draft.steps[0].id;pdRender()",ctx);
  assert.equal(nodes.designerActorAction.value,'OFF');
  nodes.designerActorAction.value='PWM';nodes.designerActorAction.events.change();
  assert.equal(vm.runInContext('pd.draft.steps[0].Rast',ctx),'Ruehrwerk:100');
  for(const power of ['20','37','100']){
    nodes.designerActorPower.value=power;nodes.designerActorPower.events.change();
    assert.equal(vm.runInContext('pd.draft.steps[0].Rast',ctx),'Ruehrwerk:'+power);
  }
  nodes.designerActorPower.value='101';nodes.designerActorPower.events.change();
  assert.equal(vm.runInContext('pd.draft.steps[0].Rast',ctx),'Ruehrwerk:100');
  for(const action of ['ON','OFF']){
    nodes.designerActorAction.value=action;nodes.designerActorAction.events.change();
    assert.equal(vm.runInContext('pd.draft.steps[0].Rast',ctx),'Ruehrwerk:'+action);
  }
  vm.runInContext('pd.draft.snapshot.actors[0].PWMSW=false;pdRender()',ctx);
  assert.deepEqual(nodes.designerActorAction.children.map(n=>n.value),['ON','OFF']);
  await vm.runInContext('pdSave()',ctx);
  const versionBase=vm.runInContext('pd.draft.id',ctx);
  await vm.runInContext('pdSaveChoice()',ctx);
  assert.equal(nodes.designerDialog.children[1].children.length,3);
  await nodes.designerDialog.children[1].children[1].click();
  assert.equal(vm.runInContext('pd.draft.version',ctx),2);
  assert.ok(saved.has(versionBase));
  await vm.runInContext('pdDrafts()',ctx);
  const draftBody=nodes.designerDialog.children[1];
  assert.ok(!draftBody.children.some(n=>n.tag==='input'));
  const draftTable=draftBody.children[0].children[0],draftRows=draftTable.children[1];
  const draftUpdated=draftTable.children[0].children[0].children[2];
  await draftUpdated.children[0].click();assert.equal(draftUpdated.attributes['aria-sort'],'ascending');
  await draftUpdated.children[0].click();assert.equal(draftUpdated.attributes['aria-sort'],'descending');
  assert.equal(draftUpdated.children[0].children[0].textContent,'▾');
  const grouped=draftRows.children.find(row=>row.className==='version-group');
  assert.ok(grouped);
  await grouped.children[0].children[0].click();
  const versionRow=draftRows.children.filter(row=>row.className==='explorer-version-row').at(-1);
  assert.ok(versionRow);
  await versionRow.children[3].children[0].click();
  assert.ok(!saved.has(versionBase));assert.ok(saved.has('new-version-id'));
  vm.runInContext("pd.draft.snapshot={actors:[],kettles:[{name:'Braukessel',enabled:1},{name:'Sud',enabled:1},{name:'Nachguss',enabled:1},{name:'Fermenter',enabled:1}],profiles:{'Aufheizen.json':{},'Kochen.json':{}}};pd.draft.steps=[{...PlanDesigner.step('IDS:ON',0,10,false),editor:{type:'kettle'}}];pd.selected=pd.draft.steps[0].id;pdRender()",ctx);
  nodes.designerKettleOperation.value='threshold';nodes.designerKettleOperation.events.change();
  assert.equal(vm.runInContext('pd.draft.steps[0].Rast',ctx),'MAISCHETHRESOUT:100');
  assert.equal(vm.runInContext('pd.draft.steps[0].Dauer',ctx),0);
  assert.equal(vm.runInContext('pd.draft.steps[0].autonext',ctx),true);
  assert.ok(!nodes.designerProperties.children.some(label=>label.textContent==='Dauer min'||label.textContent==='Aktion'));

  nodes.designerKettlePower.value='37';nodes.designerKettlePower.events.change();
  assert.equal(vm.runInContext('pd.draft.steps[0].Rast',ctx),'MAISCHETHRESOUT:37');
  vm.runInContext("pd.draft.steps[0].Rast='IDSPROFIL:Aufheizen';pdRender()",ctx);
  nodes.designerProfileName.value='Kochen';nodes.designerProfileName.events.change();
  assert.equal(vm.runInContext('pd.draft.steps[0].Rast',ctx),'IDSPROFIL:Kochen');
  nodes.designerProfileTarget.value='local:kettle:2';nodes.designerProfileTarget.events.change();
  assert.equal(vm.runInContext('pd.draft.steps[0].Rast',ctx),'HLTPROFIL:Kochen');
  vm.runInContext("pd.draft.steps[0].Rast='HEATER:OFF';delete pd.draft.steps[0].resource;pdRender()",ctx);
  nodes.designerKettleOperation.value='cooler';nodes.designerKettleOperation.events.change();
  nodes.designerKettleAction.value='ON';nodes.designerKettleAction.events.change();
  assert.equal(vm.runInContext('pd.draft.steps[0].Rast',ctx),'COOLER:ON');
  assert.ok(!nodes.designerSidebar.children.flatMap(g=>g.children).some(n=>n.textContent==='Sonderbefehl'));
  vm.runInContext("pd.draft.snapshot.kettles[1].enabled=0;pd.draft.steps[0].Rast='IDSPROFIL:Aufheizen';pdRender()",ctx);
  assert.ok(!nodes.designerSidebar.children.flatMap(g=>g.children).some(n=>n.textContent==='Fermenter'||n.textContent==='Sud'));
  assert.deepEqual(nodes.designerProfileTarget.children.map(n=>n.textContent),['Braukessel','Nachguss']);
  vm.runInContext("pd.draft.steps[0].Rast='MAISCHE:100';delete pd.draft.steps[0].resource;pdRender()",ctx);
  const powerInput=nodes.designerKettlePower;powerInput.value='80';
  const savesBeforeApply=calls.filter(c=>c.url==='/api/designer/save').length;
  ctx.document.activeElement={tagName:'INPUT',form:nodes.designerProperties,dispatchEvent(){powerInput.events.change();}};
  nodes.designerApplyProperties.click();
  assert.equal(vm.runInContext('pd.draft.steps[0].Rast',ctx),'MAISCHE:80');
  assert.equal(calls.filter(c=>c.url==='/api/designer/save').length,savesBeforeApply);
  await vm.runInContext('pdKbhSource()',ctx);
  const kbhHeader=nodes.designerDialog.children[0],filters=kbhHeader.children[1],search=kbhHeader.children[2];
  assert.equal(kbhHeader.children[0].textContent,'kleinerBrauhelfer2');
  const kbhRows=nodes.designerDialog.children[1].children[0].children[0].children[1];
  assert.equal(kbhRows.children.length,3);
  assert.equal(kbhRows.children[0].children.length,4);
  assert.match(kbhRows.children[0].children[3].textContent,/2026/);
  const allStages=filters.children[0].children[0];allStages.checked=false;allStages.events.change();
  assert.equal(kbhRows.children.length,0);
  const bottled=filters.children[3].children[0];bottled.checked=true;bottled.events.change();
  assert.equal(kbhRows.children.length,1);assert.equal(kbhRows.children[0].children[0].children[0].textContent,'Batch 2');
  assert.equal(allStages.indeterminate,true);
  allStages.checked=true;allStages.events.change();
  const watchlist=filters.children[4].children[0];assert.equal(watchlist.checked,false);
  watchlist.checked=true;watchlist.events.change();
  assert.equal(kbhRows.children.length,1);assert.equal(kbhRows.children[0].children[0].children[0].textContent,'Batch 1');
  const brewed=filters.children[2].children[0];brewed.checked=false;brewed.events.change();
  assert.equal(kbhRows.children.length,0);
  watchlist.checked=false;watchlist.events.change();allStages.checked=true;allStages.events.change();
  search.value='12';search.events.input();
  assert.equal(kbhRows.children.length,1);assert.equal(kbhRows.children[0].children[0].children[0].textContent,'Batch 2');
  legacyKbh=true;await vm.runInContext('pdKbhSource()',ctx);
  const legacyRows=nodes.designerDialog.children[1].children[0].children[0].children[1];
  assert.equal(legacyRows.children.length,1);
  assert.equal(legacyRows.children[0].children[2].textContent,'—');
  assert.equal(nodes.designerDialog.children[0].children[1].children[0].children[0].disabled,true);
  assert.match(nodes.designerDialogFeedback.textContent,/ServiceTool neu starten/);
  await vm.runInContext('pdBrewfatherSource()',ctx);
  const bfHeader=nodes.designerDialog.children[0],bfChecks=bfHeader.children[1],bfSearch=bfHeader.children[2];
  const bfTable=nodes.designerDialog.children[1].children[0].children[0],bfRows=bfTable.children[1];
  assert.equal(bfRows.children[0].children[0].children[0].textContent,'Amber');
  bfTable.children[0].children[0].children[0].children[0].click();
  assert.equal(bfRows.children[0].children[0].children[0].textContent,'Zebra');
  assert.equal(bfTable.children[0].children[0].children.length,5);
  assert.equal(bfRows.children[0].children[3].textContent,'Porter');
  assert.equal(bfRows.children[0].children[4].textContent,'Anna');
  const bfSort=index=>bfTable.children[0].children[0].children[index].children[0].click();
  const bfName=index=>bfRows.children[index].children[0].children[0].textContent;
  bfSort(1);assert.equal(bfName(0),'Zebra');assert.equal(bfName(2),'Missing');
  bfSort(1);assert.equal(bfName(0),'Amber');assert.equal(bfName(2),'Missing');
  assert.equal(bfRows.children[2].children[1].textContent,'—');
  bfSort(2);assert.equal(bfName(0),'Amber');
  bfSort(3);assert.equal(bfName(0),'Amber');
  bfSort(4);assert.equal(bfName(0),'Zebra');
  for(const query of ['porter','anna']){bfSearch.value=query;bfSearch.events.input();assert.equal(bfRows.children.length,1);assert.equal(bfName(0),'Zebra');}
  bfSearch.value='';bfSearch.events.input();
  assert.equal(vm.runInContext("pdBrewfatherTime('invalid')",ctx),null);
  assert.equal(vm.runInContext('pdBrewfatherTime({})',ctx),null);
  assert.equal(vm.runInContext('pdBrewfatherTime(1700000000)',ctx),1700000000000);
  const batches=bfChecks.children[0].children[0],recipes=bfChecks.children[1].children[0];
  batches.checked=true;await batches.events.change();
  assert.equal(recipes.checked,false);assert.equal(batches.checked,true);
  assert.equal(bfRows.children[0].children[2].textContent,'Amber');
  bfSearch.value='unknown';bfSearch.events.input();assert.equal(bfRows.children.length,0);
  bfSearch.value='7';bfSearch.events.input();assert.equal(bfRows.children.length,1);
  batches.checked=false;batches.events.change();assert.equal(batches.checked,true);
  vm.runInContext("pd.draft=PlanDesigner.create();pd.draft.name='Links';pd.draft.steps=[PlanDesigner.step('Rast',63,30)];pd.comparison=PlanDesigner.create();pd.comparison.name='Rechts';pd.comparison.steps=[PlanDesigner.step('Pumpe:ON'),PlanDesigner.step('Rast',63,45)];pdRender()",ctx);
  const comparison=nodes.designerComparison;
  const compareTable=comparison.children[0].children[0],compareHead=compareTable.children[0],compareRows=compareTable.children[1];
  assert.equal(compareHead.children[0].children[0].children[0].textContent,'Aktueller Maischeplan');
  assert.equal(compareHead.children[0].children[2].children[0].textContent,'Vergleichsplan');
  assert.equal(compareHead.children[1].children.length,10);
  assert.equal(compareRows.children[0].children[0].textContent,'—');
  const take=compareRows.children[0].children[1].children[0];
  assert.equal(take.textContent,'');assert.equal(take.children[0].className,'icon-arrow-left2');assert.match(take.title,/links übernehmen/);take.click();
  assert.equal(vm.runInContext('pd.draft.steps[0].Rast',ctx),'Pumpe:ON');
  assert.equal(vm.runInContext('pd.comparison.steps.length',ctx),2);
  assert.notEqual(vm.runInContext('pd.draft.steps[0].id',ctx),vm.runInContext('pd.comparison.steps[0].id',ctx));
  assert.equal(nodes.designerCompareToggle.title,'Vergleich beenden');
  assert.equal(nodes.designerCompareToggle.className,'danger explorer-icon');
  assert.equal(nodes.designerCompareToggle.children[0].className,'icon-cross');
  await nodes.designerCompareToggle.click();
  assert.equal(comparison.hidden,true);assert.equal(nodes.designerSteps.hidden,false);
  assert.equal(nodes.designerCompareToggle.title,'Maischeplan vergleichen');
  assert.equal(nodes.designerCompareToggle.className,'info explorer-icon');
  assert.equal(nodes.designerCompareToggle.children[0].className,'icon-copy');
  const originalPicker=vm.runInContext('pdPickFile',ctx);
  vm.runInContext("pdPickFile=callback=>callback({misc:[{Sudname:'File comparison'}]})",ctx);
  await nodes.designerCompareToggle.click();
  assert.equal(nodes.designerDialog.open,true);
  await nodes.designerCompareFile.click();
  assert.equal(nodes.designerDialog.open,false);
  ctx.originalPicker=originalPicker;vm.runInContext('pdPickFile=originalPicker',ctx);
  assert.equal(nodes.designerCompareToggle.children[0].className,'icon-cross');
  assert.equal(nodes.designerCompareToggle.children[0].className,'icon-cross');
  assert.equal(nodes.designerCompareToggle.className,'danger explorer-icon');
  assert.equal(nodes.designerCompareToggle.title,'Vergleich beenden');
  await nodes.designerCompareToggle.click();
  assert.equal(vm.runInContext('pd.comparison',ctx),null);
  assert.equal(nodes.designerCompareToggle.children[0].className,'icon-copy');

  vm.runInContext("pd.draft=PlanDesigner.create();pd.draft.snapshot={complete:true,captured_at:Date.now()/1000};pd.draft.steps=[PlanDesigner.step('Rast',63,30,false)];pdReview()",ctx);
  const reviewCheck=nodes.designerReviewAutonext;
  const reviewBody=()=>nodes.designerReviewResults.children[0].children[0].children[1];
  assert.equal(reviewCheck.checked,false);
  assert.match(reviewBody().children[0].children[0].textContent,/Keine Hinweise/);
  reviewCheck.checked=true;reviewCheck.events.change();
  assert.match(reviewBody().children[0].children[1].textContent,/Benutzerfreigabe/);
  reviewCheck.checked=false;reviewCheck.events.change();
  assert.match(reviewBody().children[0].children[0].textContent,/Keine Hinweise/);
  assert.equal(vm.runInContext('pd.draft.steps[0].autonext',ctx),false);
  vm.runInContext('pd.selected=null;pdProperties()',ctx);
  assert.equal(nodes.designerEnzymeminh.value,0);
  nodes.designerEnzymeminh.value='50.5';nodes.designerEnzymeminh.events.change();
  nodes.designerEnzymemaxh.value='75';nodes.designerEnzymemaxh.events.change();
  assert.equal(vm.runInContext('pd.draft.misc.minh',ctx),50.5);
  assert.equal(vm.runInContext('pd.draft.misc.maxh',ctx),75);
  nodes.designerEnzymemaxh.value='';nodes.designerEnzymemaxh.events.change();
  assert.equal(vm.runInContext('pd.draft.misc.maxh',ctx),75);
  vm.runInContext("pd.draft=PlanDesigner.create();pd.draft.snapshot={profiles:{'MasterOnly.json':{}},remote:{workers:[{id:'w',host:'worker',profiles:{'WorkerProfile.json':{}},kettles:[{slot:2,name:'Hlt',selected:true},{slot:1,name:'Unused',selected:false}]}]}};pdInsert(PlanDesigner.resources(pd.draft.snapshot).find(r=>r.kind==='kettle'&&r.assigned))",ctx);
  const beforeInsert=vm.runInContext('pd.draft.steps.length',ctx);
  vm.runInContext("pdInsert(PlanDesigner.resources(pd.draft.snapshot).find(r=>r.kind==='kettle'&&!r.assigned))",ctx);
  assert.equal(vm.runInContext('pd.draft.steps.length',ctx),beforeInsert);
  assert.ok(!nodes.designerKettleOperation.children.some(option=>option.value==='profile'));
  vm.runInContext("pdInsert(PlanDesigner.resources(pd.draft.snapshot).find(r=>r.kind==='profile'&&r.remote))",ctx);
  assert.equal(nodes.designerProfileName.tag,'input');
  nodes.designerProfileName.value='WorkerProfile';nodes.designerProfileName.events.change();
  assert.equal(vm.runInContext('pd.draft.steps.at(-1).Rast',ctx),'worker/HLTPROFIL:WorkerProfile');
  await vm.runInContext('pdPublish()',ctx);
  const publishBody=nodes.designerDialog.children[1];
  publishBody.children[0].children[0].value='Finished';
  assert.equal(publishBody.children[1].children[0].value,'version');
  await publishBody.children[3].click();
  assert.equal(calls.at(-1).url,'/api/designer/inventory-publish');
  assert.equal(calls.at(-1).body.draft.name,'Finished');
  assert.equal(calls.at(-1).body.replace,false);
  assert.equal(vm.runInContext('pd.dirty',ctx),false);
  assert.equal(nodes.designerDialog.open,false);
  vm.runInContext("pd.dirty=true;pd.draft.name='Keep saved'",ctx);
  const oldId=vm.runInContext('pd.draft.id',ctx);
  const saveAndOpen=vm.runInContext('pdAccept(PlanDesigner.create())',ctx);
  await nodes.designerUnsavedDialog.children[4].children[0].click();
  assert.equal(await saveAndOpen,true);assert.equal(saved.get(oldId).name,'Keep saved');
  vm.runInContext("pd.dirty=true;pd.draft.name='Discard'",ctx);
  const countBefore=calls.length;
  nodes.designerStatus.textContent='Entwurf gespeichert.';
  const discardAndOpen=vm.runInContext('pdAccept(PlanDesigner.create())',ctx);
  nodes.designerUnsavedDialog.children[4].children[1].click();
  assert.equal(await discardAndOpen,true);assert.equal(calls.length,countBefore);
  assert.equal(nodes.designerStatus.textContent,'');
  vm.runInContext('pd.dirty=true',ctx);
  const escape=vm.runInContext('pdAccept(PlanDesigner.create())',ctx);
  nodes.designerUnsavedDialog.oncancel({preventDefault(){}});
  assert.equal(await escape,false);
  vm.runInContext("pd.draft=PlanDesigner.create();pd.draft.steps=[PlanDesigner.step('First'),PlanDesigner.step('Second')];pd.dirty=false;pdRender()",ctx);
  nodes.designerSteps.children[0].click();
  assert.equal(nodes.designerSteps.children[0].focused,true);
  nodes.designerSteps.children[0].events.keydown({key:'Delete',preventDefault(){}});
  assert.equal(vm.runInContext('pd.draft.steps.length',ctx),1);
  assert.equal(vm.runInContext('pd.draft.steps[0].Rast',ctx),'Second');
  assert.equal(nodes.designerSteps.children[0].focused,true);
  vm.runInContext('pdHistory("undo","redo")',ctx);
  assert.equal(vm.runInContext('pd.draft.steps.length',ctx),2);
  vm.runInContext("pd.draft=PlanDesigner.create();pd.draft.steps=[PlanDesigner.step('First'),PlanDesigner.step('Last')];pd.selected=pd.draft.steps[0].id;pdRender()",ctx);
  const insertEvent={key:'Insert',target:{tagName:'DIV'},preventDefault(){}};
  nodes.designerPanel.events.keydown(insertEvent);
  assert.equal(vm.runInContext('pd.draft.steps[1].Rast',ctx),'Neue Rast');
  assert.equal(vm.runInContext('pd.draft.steps[2].Rast',ctx),'Last');
  assert.equal(nodes.designerSteps.children[1].focused,true);
  vm.runInContext('pd.selected=null',ctx);
  nodes.designerPanel.events.keydown(insertEvent);
  assert.equal(vm.runInContext('pd.draft.steps.length',ctx),4);
  assert.equal(vm.runInContext('pd.draft.steps[3].Rast',ctx),'Neue Rast');
  nodes.designerPanel.events.keydown({...insertEvent,target:{tagName:'INPUT'}});
  assert.equal(vm.runInContext('pd.draft.steps.length',ctx),4);
  vm.runInContext('pdHistory("undo","redo")',ctx);
  assert.equal(vm.runInContext('pd.draft.steps.length',ctx),3);
  vm.runInContext("pd.draft=PlanDesigner.create();pdInsert({label:'Kochen',type:'boil',temp:100,duration:15});pdInsert({label:'Hopfengabe',type:'hop',temp:100,duration:50})",ctx);
  const propertyInput=label=>nodes.designerProperties.children.find(n=>n.textContent===label).children[0];
  assert.equal(vm.runInContext('pd.draft.steps[1].Temperatur',ctx),98);
  assert.equal(propertyInput('Vorlage').value,'boil');
  propertyInput('Vorlage').value='first_wort';propertyInput('Vorlage').events.change();
  assert.equal(vm.runInContext('pd.draft.steps[1].Temperatur',ctx),78);
  propertyInput('Vorlage').value='whirlpool';propertyInput('Vorlage').events.change();
  assert.equal(vm.runInContext('pd.draft.steps[1].Temperatur',ctx),80);
  propertyInput('Vorlage').value='boil';propertyInput('Vorlage').events.change();
  assert.equal(vm.runInContext('pd.draft.steps[1].Dauer',ctx),50);
  propertyInput('Name').value='Perle';propertyInput('Name').events.change();
  propertyInput('Menge g').value='23.123';propertyInput('Menge g').events.change();
  assert.equal(vm.runInContext('pd.draft.steps[1].Rast',ctx),'Perle 23.1 g');
  propertyInput('Dauer min').value='40';propertyInput('Dauer min').events.change();
  assert.equal(vm.runInContext('pd.draft.steps[0].Dauer',ctx),15);
  assert.equal(vm.runInContext('pd.draft.steps[1].Dauer',ctx),40);
  assert.equal(vm.runInContext('pd.draft.steps[0].Rast',ctx),'Kochen');
  assert.ok(!nodes.designerProperties.children.some(n=>/Zeitbezug|vor Kochende/.test(n.textContent)));
  vm.runInContext("pdInsert({label:'Rast',type:'rest'})",ctx);
  propertyInput('Vorlage').value='malt';propertyInput('Vorlage').events.change();
  assert.equal(vm.runInContext('pd.draft.steps.at(-1).Temperatur',ctx),63);
  assert.equal(vm.runInContext('pd.draft.steps.at(-1).Dauer',ctx),0);
  assert.equal(propertyInput('Vorlage').value,'malt');
  propertyInput('Vorlage').value='after';propertyInput('Vorlage').events.change();
  assert.equal(vm.runInContext('pd.draft.steps.at(-1).Temperatur',ctx),0);
  assert.equal(vm.runInContext('pd.draft.steps.at(-1).Rast',ctx),'Nachisomerisierung');
  assert.equal(vm.runInContext('pd.draft.steps.at(-1).autonext',ctx),true);
  vm.runInContext('pd.draft.misc.Kochdauer=75;pd.selected=null;pdRender()',ctx);
  assert.ok(nodes.designerProperties.children.some(n=>n.textContent.includes('laut Plan 75 min, laut Schritten 55 min')));
  vm.runInContext('pd.draft.misc.Kochdauer=0;pdRender()',ctx);
  assert.ok(!nodes.designerProperties.children.some(n=>n.textContent.startsWith('Hinweis: Kochzeit')));
  vm.runInContext("pdInsert({label:'Rast',type:'rest'})",ctx);
  const tempField=propertyInput('Temperatur °C');tempField.value='67';
  let tabPrevented=false;
  nodes.designerProperties.events.keydown({key:'Tab',target:tempField,preventDefault(){tabPrevented=true;}});
  assert.equal(tabPrevented,true);
  assert.equal(vm.runInContext('pd.draft.steps.at(-1).Temperatur',ctx),67);
  assert.equal(propertyInput('Dauer min').focused,true);
  const durationField=propertyInput('Dauer min');durationField.value='25';
  nodes.designerProperties.events.keydown({key:'Tab',shiftKey:true,target:durationField,preventDefault(){}});
  assert.equal(vm.runInContext('pd.draft.steps.at(-1).Dauer',ctx),25);
  assert.equal(propertyInput('Temperatur °C').focused,true);
  vm.runInContext('pdMarkClean();pd.undo=[];pd.redo=[]',ctx);
  vm.runInContext('pdChange(()=>{})',ctx);
  assert.equal(vm.runInContext('pd.dirty',ctx),false);
  assert.equal(vm.runInContext('pd.undo.length',ctx),0);
  vm.runInContext('pdChange(()=>pd.draft.steps.at(-1).Dauer=30)',ctx);
  assert.equal(vm.runInContext('pd.dirty',ctx),true);
  vm.runInContext('pdHistory("undo","redo")',ctx);
  assert.equal(vm.runInContext('pd.dirty',ctx),false);
  vm.runInContext('pdHistory("redo","undo")',ctx);
  assert.equal(vm.runInContext('pd.dirty',ctx),true);
  vm.runInContext('pdChange(()=>pd.draft.steps.at(-1).Dauer=25)',ctx);
  assert.equal(vm.runInContext('pd.dirty',ctx),false);
  vm.runInContext("pd.draft=PlanDesigner.create();pd.draft.steps=[PlanDesigner.step('First'),PlanDesigner.step('Last')];pd.selected=pd.draft.steps[0].id;pdRender()",ctx);
  nodes.designerSidebar.children.flatMap(g=>g.children).find(n=>n.textContent==='Rast').click();
  assert.equal(vm.runInContext('pd.draft.steps[1].Rast',ctx),'Rast');
  assert.equal(vm.runInContext('pd.draft.steps[2].Rast',ctx),'Last');
  vm.runInContext("pd.selected=pd.draft.steps[0].id;pdInsertAfterSelected({kind:'actor',name:'Pumpe',command:'Pumpe',key:'pump'})",ctx);
  assert.equal(vm.runInContext('pd.draft.steps[1].Rast',ctx),'Pumpe:OFF');
  vm.runInContext('pd.selected=null;pdRender()',ctx);
  nodes.designerSidebar.children.flatMap(g=>g.children).find(n=>n.textContent==='Rast').click();
  assert.equal(vm.runInContext('pd.draft.steps.at(-1).Rast',ctx),'Rast');
  vm.runInContext("pd.draft.dock=[PlanDesigner.step('Dock first'),PlanDesigner.step('Dock last')];pd.selected=pd.draft.dock[0].id;pdRender()",ctx);
  nodes.designerSidebar.children.flatMap(g=>g.children).find(n=>n.textContent==='Rast').click();
  assert.equal(vm.runInContext('pd.draft.dock[1].Rast',ctx),'Rast');
  assert.equal(vm.runInContext('pd.draft.dock[2].Rast',ctx),'Dock last');
  vm.runInContext("pd.draft=PlanDesigner.create();pd.draft.steps=['A','B','C','D'].map(n=>PlanDesigner.step(n));pd.selected=null;pdRender()",ctx);
  nodes.designerSteps.children[1].click();
  nodes.designerSteps.children[3].events.click({shiftKey:true});
  assert.equal(vm.runInContext('pdSelectedIds().length',ctx),3);
  assert.equal(nodes.designerSteps.children[1].attributes['aria-selected'],'true');
  assert.equal(nodes.designerSteps.attributes['aria-multiselectable'],'true');
  let dragged;
  nodes.designerSteps.children[2].events.dragstart({dataTransfer:{setData(type,value){dragged=value;}}});
  const dropEvent={preventDefault(){},stopPropagation(){},dataTransfer:{getData(){return dragged;}}};
  nodes.designerDock.events.drop(dropEvent);
  assert.equal(vm.runInContext('pd.draft.steps.map(s=>s.Rast).join()',ctx),'A');
  assert.equal(vm.runInContext('pd.draft.dock.map(s=>s.Rast).join()',ctx),'B,C,D');
  nodes.designerDock.children[0].events.dragstart({dataTransfer:{setData(type,value){dragged=value;}}});
  nodes.designerSteps.children[0].events.drop(dropEvent);
  assert.equal(vm.runInContext('pd.draft.steps.map(s=>s.Rast).join()',ctx),'B,C,D,A');
  nodes.designerSteps.children[0].events.keydown({key:'Delete',preventDefault(){}});
  assert.equal(vm.runInContext('pd.draft.steps.map(s=>s.Rast).join()',ctx),'A');
  vm.runInContext('pdHistory("undo","redo")',ctx);
  assert.equal(vm.runInContext('pd.draft.steps.map(s=>s.Rast).join()',ctx),'B,C,D,A');
  nodes.designerSteps.children[0].click();
  nodes.designerSteps.children[2].events.click({ctrlKey:true});
  assert.equal(vm.runInContext('pdSelectedIds().length',ctx),2);
  nodes.designerSteps.children[0].events.click({ctrlKey:true});
  assert.equal(vm.runInContext('pdSelectedIds().length',ctx),1);
  vm.runInContext('pd.dirty=true;pd.allowUnload=false',ctx);
  let unloadPrevented=false;
  windowEvents.beforeunload({preventDefault(){unloadPrevented=true;}});
  assert.equal(unloadPrevented,true);
  vm.runInContext('pd.allowUnload=true',ctx);unloadPrevented=false;
  windowEvents.beforeunload({preventDefault(){unloadPrevented=true;}});
  assert.equal(unloadPrevented,false);
  vm.runInContext('pd.selected=null;pdRender()',ctx);
  const boilInput=nodes.designerProperties.children.find(n=>n.textContent==='Kochdauer min').children[0];
  boilInput.value='83';boilInput.tagName='INPUT';boilInput.form=nodes.designerProperties;
  boilInput.dispatchEvent=event=>boilInput.events[event.type]();
  nodes.designerProperties.events.input({target:boilInput});
  // A browser popup has already taken focus; no blur/change event arrived.
  ctx.document.activeElement=null;
  nodes.designerApplyProperties.click();
  assert.equal(vm.runInContext('pd.draft.misc.Kochdauer',ctx),83);
  assert.equal(nodes.designerProperties.tag,'form');
  assert.equal(nodes.designerBrewfatherForm.tag,'form');
  const sidebarGroups=nodes.designerSidebar.children;
  assert.deepEqual(sidebarGroups.map(g=>g.dataset.group),['steps','sources','kettle','actor','profile','sensor','snapshot']);
  assert.ok(sidebarGroups.every(g=>g.tag==='details'&&g.open&&g.children[0].tag==='summary'));
  sidebarGroups[1].open=false;sidebarGroups[1].events.toggle();
  vm.runInContext('pdRender()',ctx);
  assert.equal(nodes.designerSidebar.children[1].open,false);
  assert.equal(nodes.designerSidebar.children[0].open,true);
  vm.runInContext("currentLang='en';pdRender()",ctx);
  assert.equal(nodes.designerSidebar.children[1].open,false);
  assert.equal(nodes.designerSidebar.children[1].children[0].textContent,'Sources');
  nodes.designerSidebar.children[1].open=true;nodes.designerSidebar.children[1].events.toggle();
  vm.runInContext("currentLang='de';pdRender()",ctx);
  assert.equal(nodes.designerSidebar.children[1].open,true);
  // Shared dock survives plan changes and reloads; copying never consumes templates.
  await vm.runInContext('pd.dockWrite',ctx);
  vm.runInContext("pd.dirty=false;pd.draft.dock=[{...PlanDesigner.step('worker/Pumpe:ON'),resource:'worker:actor:0',dockSaved:true}];pdPersistDock()",ctx);
  await vm.runInContext('pd.dockWrite',ctx);
  await vm.runInContext('pdAccept(PlanDesigner.create())',ctx);
  assert.equal(vm.runInContext('pd.draft.dock[0].Rast',ctx),'worker/Pumpe:ON');
  vm.runInContext('pd.draft.dock=[];pd.dockReady=null',ctx);
  await vm.runInContext('pdLoadDock()',ctx);
  assert.equal(vm.runInContext('pd.draft.dock.length',ctx),1);
  const originalDockId=vm.runInContext('pd.draft.dock[0].id',ctx);
  assert.equal(nodes.designerDockTabs.children.length,2);
  assert.equal(nodes.designerDock.children.length,0);
  nodes.designerDockTabs.children[1].click();
  assert.equal(nodes.designerDockTools.children.some(b=>b.title.includes('leeren')),false);
  assert.equal(nodes.designerDock.children[0].children.at(-1).title,'Eintrag löschen');
  await nodes.designerDockTools.children[0].click();
  assert.equal(nodes.designerProperties.hidden,true);
  await nodes.designerDockTools.children[0].click();
  assert.equal(nodes.designerProperties.hidden,false);
  assert.equal(nodes.designerDock.children[0].children[0].children.length,0); // no checkbox
  nodes.designerDock.children[0].click();
  assert.equal(nodes.designerDock.children[0].focused,true);
  nodes.designerDock.children[0].events.keydown({key:'Delete',preventDefault(){}});
  await vm.runInContext('pd.dockWrite',ctx);
  assert.equal(persistedDock.length,0);
  assert.equal(vm.runInContext('pd.draft.steps.length',ctx),0);
  vm.runInContext('pdHistory("undo","redo")',ctx);await vm.runInContext('pd.dockWrite',ctx);
  assert.equal(persistedDock.length,1);
  let dockDrag;
  nodes.designerDock.children[0].events.dragstart({dataTransfer:{setData(type,value){dockDrag=value;}}});
  nodes.designerSteps.events.drop({preventDefault(){},stopPropagation(){},dataTransfer:{getData(){return dockDrag;}}});
  assert.equal(vm.runInContext('pd.draft.dock.length',ctx),1);
  assert.notEqual(vm.runInContext('pd.draft.steps[0].id',ctx),originalDockId);
  assert.equal(vm.runInContext('pd.draft.steps[0].resource',ctx),'worker:actor:0');
  vm.runInContext('pd.dirty=false',ctx);
  await vm.runInContext("pdAccept({...PlanDesigner.create(),dock:[PlanDesigner.step('Ende')]})",ctx);
  assert.equal(vm.runInContext('pd.draft.dock.length',ctx),1);
  assert.equal(vm.runInContext('pd.pendingDock.length',ctx),1);
  nodes.designerDockNotice.children[1].click();
  await vm.runInContext('pd.dockWrite',ctx);
  assert.equal(persistedDock.length,1);
  assert.equal(vm.runInContext('pd.dirty',ctx),false);
  await vm.runInContext('pdAccept({...PlanDesigner.create(),dock:PlanDesigner.clone(pd.draft.dock)})',ctx);
  assert.equal(vm.runInContext('pd.pendingDock.length',ctx),0);
  nodes.designerDockTabs.children[0].click();
  assert.equal(nodes.designerDock.children.length,1);
  await nodes.designerDockTools.children.find(b=>b.title==='Ablage leeren').click();
  await vm.runInContext('pd.dockWrite',ctx);assert.equal(persistedDock.length,1);
  assert.equal(nodes.designerDock.children.length,0);
  vm.runInContext('pdHistory("undo","redo")',ctx);await vm.runInContext('pd.dockWrite',ctx);assert.equal(persistedDock.length,1);

  assert.equal(vm.runInContext("exVersionGroups([{type:'file',name:'Single.json',kind:'mashplan'}],true)[0].versions.length",ctx),0);
  // The same draft table can be embedded in Explorer without opening a modal.
  saved.clear();vm.runInContext("pd.draft.name='Explorer draft';pdMarkClean()",ctx);await vm.runInContext('pdSave()',ctx);
  ctx.externalDrafts=new Element();let explorerOpened=false;ctx.onExplorerOpen=()=>{explorerOpened=true;};
  nodes.designerDialog.close();
  await vm.runInContext('pdDrafts(false,{container:externalDrafts,onOpen:onExplorerOpen})',ctx);
  assert.equal(nodes.designerDialog.open,false);
  const embeddedRows=ctx.externalDrafts.children[1].children[0].children[1];
  await embeddedRows.children[0].children[0].children[0].click();
  assert.equal(explorerOpened,true);assert.equal(vm.runInContext('pd.draft.name',ctx),'Explorer draft');
  // Device sources stay unavailable offline and reject stale or failed requests.
  const originalApi=ctx.api;let deviceReads=0;
  ctx.managementDeviceAvailable=()=>false;
  ctx.api=async()=>{deviceReads++;throw new Error('getaddrinfo failed');};
  await assert.rejects(vm.runInContext('pdDevicePlans()',ctx),/Keine Netzwerkverbindung/);
  assert.equal(deviceReads,0);
  ctx.managementDeviceAvailable=()=>true;
  await assert.rejects(vm.runInContext('pdDevicePlans()',ctx),/konnte nicht aufgelöst werden/);
  assert.equal(deviceReads,1);
  let finishDeviceRead;
  ctx.api=()=>new Promise(resolve=>{finishDeviceRead=resolve;});
  const pendingDevicePlans=vm.runInContext('pdDevicePlans()',ctx);
  const previousDevice=ctx.appConfig.active_device_id;
  ctx.appConfig.active_device_id='other-device';finishDeviceRead({files:[]});
  await assert.rejects(pendingDevicePlans,/Gerät wurde gewechselt/);
  ctx.appConfig.active_device_id=previousDevice;ctx.api=originalApi;
  // Import diagnostics live outside properties; clearing does not edit the plan.
  vm.runInContext("pd.draft.steps=[{...PlanDesigner.step('Imported'),original:{source:'example'}}];pd.selected=pd.draft.steps[0].id;pd.selection=[pd.selected];pdRender()",ctx);
  assert.match(nodes.designerImportStatus.textContent,/example/);
  assert.ok(!nodes.designerProperties.children.some(node=>node.tagName==='details'));
  let copiedImportData;ctx.copyOutputLog=async id=>{copiedImportData=nodes[id].textContent;};
  await nodes.designerImportCopy.click();assert.match(copiedImportData,/example/);
  await nodes.designerImportClear.click();vm.runInContext('pdRender()',ctx);
  assert.equal(nodes.designerImportStatus.textContent,'');
  assert.equal(vm.runInContext('pd.draft.steps[0].original.source',ctx),'example');
  vm.runInContext('pd.selected=null;pd.selection=[];pdRender();pd.selected=pd.draft.steps[0].id;pd.selection=[pd.selected];pdRender()',ctx);
  assert.match(nodes.designerImportStatus.textContent,/example/);
  // An imported special command stays a special command when its action changes.
  vm.runInContext("pd.draft.steps=[PlanDesigner.step('HLT:ON',78)];pd.selected=pd.draft.steps[0].id;pd.selection=[pd.selected];pdRender()",ctx);
  const hasFunction=()=>nodes.designerProperties.children.some(label=>label.children.some(child=>child.id==='designerKettleOperation'));
  assert.equal(hasFunction(),false);
  nodes.designerKettleAction.value='OFF';nodes.designerKettleAction.events.change();
  assert.equal(vm.runInContext('pd.draft.steps[0].Rast',ctx),'HLT:OFF');
  assert.equal(hasFunction(),false);
  vm.runInContext("pdInsert({kind:'kettle',key:'local:kettle:2',slot:2,name:'HLT'})",ctx);
  assert.equal(hasFunction(),true);
  vm.runInContext("pdInsert({kind:'actor',key:'local:actor:0',command:'Pumpe',name:'Pumpe',temp:65,duration:15})",ctx);
  assert.equal(vm.runInContext('pd.draft.steps.at(-1).Temperatur',ctx),0);
  assert.equal(vm.runInContext('pd.draft.steps.at(-1).Dauer',ctx),0);
  vm.runInContext("pdInsert({kind:'kettle',key:'local:kettle:2',slot:2,name:'HLT',temp:78,duration:10})",ctx);
  assert.ok(!nodes.designerKettleOperation.children.some(option=>option.value==='profile'));
  nodes.designerKettleOperation.value='profile';nodes.designerKettleOperation.events.change();
  assert.equal(vm.runInContext('pd.draft.steps.at(-1).Rast',ctx),'HLT:OFF');
  vm.runInContext("pdInsert({kind:'profile',name:'Kochen',key:'profile:Kochen',temp:78,duration:10})",ctx);
  assert.equal(vm.runInContext('pd.draft.steps.at(-1).autonext',ctx),true);
  assert.equal(vm.runInContext('pd.draft.steps.at(-1).Temperatur',ctx),0);
  assert.equal(vm.runInContext('pd.draft.steps.at(-1).Dauer',ctx),0);
  const profileNumbers=nodes.designerProperties.children.flatMap(label=>label.children).filter(node=>node.type==='number');
  assert.ok(profileNumbers.length===2&&profileNumbers.every(node=>node.readOnly));
  vm.runInContext('pd.dirty=false',ctx);
  await vm.runInContext("pdAccept({...PlanDesigner.create(),steps:[PlanDesigner.step('HLTPROFIL:Kochen',78,10)]})",ctx);
  assert.equal(vm.runInContext('pd.draft.steps[0].Temperatur',ctx),0);
  assert.equal(vm.runInContext('pd.draft.steps[0].Dauer',ctx),0);
  assert.equal(vm.runInContext('pd.dirty',ctx),true);
  vm.runInContext("pd.draft.misc.Nachiso=0;pdInsert({type:'rest',label:'Rast'})",ctx);
  let restTemplate=nodes.designerProperties.children.flatMap(label=>label.children).find(node=>node.tag==='select');
  restTemplate.value='after';restTemplate.events.change();
  assert.equal(vm.runInContext('pd.draft.steps.at(-1).Temperatur',ctx),0);
  assert.equal(vm.runInContext('pd.draft.steps.at(-1).Dauer',ctx),1);
  const afterDuration=nodes.designerProperties.children.flatMap(label=>label.children).filter(node=>node.type==='number').at(-1);
  afterDuration.value='0';afterDuration.events.change();
  assert.equal(vm.runInContext('pd.draft.steps.at(-1).Dauer',ctx),1);
  vm.runInContext('pd.draft.misc.Nachiso=10',ctx);
  restTemplate=nodes.designerProperties.children.flatMap(label=>label.children).find(node=>node.tag==='select');
  restTemplate.value='after';restTemplate.events.change();
  assert.equal(vm.runInContext('pd.draft.steps.at(-1).Dauer',ctx),10);
  assert.equal(vm.runInContext("PlanDesigner.review({...PlanDesigner.create(),steps:[PlanDesigner.step('Nachisomerisierung',98,0)]}).some(note=>note.code==='post_boil_values')",ctx),true);
  vm.runInContext("pd.draft=PlanDesigner.create();pd.draft.snapshot={kettles:[{name:'Maische',enabled:1},{name:'Sudtopf',enabled:1},{name:'Nachguss',enabled:1}]};pd.selection=[];pd.selected=null",ctx);
  for(const [slot,command] of [[0,'MAISCHETHRESOUT'],[1,'SUDTHRESOUT'],[2,'HLTTHRESOUT']]){
    ctx.testSlot=slot;
    vm.runInContext("pdInsert(PlanDesigner.resources(pd.draft.snapshot).find(r=>r.kind==='kettle'&&r.slot===testSlot))",ctx);
    assert.ok(nodes.designerKettleOperation.children.some(option=>option.value==='threshold'));
    nodes.designerKettleOperation.value='threshold';nodes.designerKettleOperation.events.change();
    assert.equal(vm.runInContext('pd.draft.steps.at(-1).Rast',ctx),command+':100');
    assert.equal(vm.runInContext('pd.draft.steps.at(-1).Dauer',ctx),0);
    assert.equal(vm.runInContext('pd.draft.steps.at(-1).autonext',ctx),true);
    assert.ok(!nodes.designerProperties.children.some(label=>label.textContent==='Dauer min'||label.textContent==='Aktion'));
  }
  for(const alias of ['IDSTHRESOUT','SudtopfTHRESOUT','NachgussTHRESOUT']){
    ctx.testAlias=alias;vm.runInContext("pd.draft.steps.at(-1).Rast=testAlias+':80';delete pd.draft.steps.at(-1).resource;pdRender()",ctx);
    nodes.designerKettlePower.value='75';nodes.designerKettlePower.events.change();
    assert.equal(vm.runInContext('pd.draft.steps.at(-1).Rast',ctx),alias+':75');
  }
  vm.runInContext("pd.draft=PlanDesigner.create();pd.draft.steps=Array.from({length:29},()=>PlanDesigner.step('Rast'));pd.selection=[];pd.selected=null;pd.undo=[];pdMarkClean();pdInsert({})",ctx);
  assert.equal(vm.runInContext('pd.draft.steps.length',ctx),30);
  const beforeLimit=vm.runInContext('JSON.stringify({draft:pd.draft,selected:pd.selected,selection:pd.selection,undo:pd.undo})',ctx);
  vm.runInContext('pdInsert({})',ctx);
  assert.equal(vm.runInContext('JSON.stringify({draft:pd.draft,selected:pd.selected,selection:pd.selection,undo:pd.undo})',ctx),beforeLimit);
  vm.runInContext("pd.draft.steps.pop();pd.draft.dock=[PlanDesigner.step('A'),PlanDesigner.step('B')];pdCopyDock(pd.draft.dock.map(s=>s.id))",ctx);
  assert.equal(vm.runInContext('pd.draft.steps.length',ctx),29);
  assert.equal(vm.runInContext('pd.draft.dock.length',ctx),2);
  assert.equal(await vm.runInContext("pdAccept({...PlanDesigner.create(),steps:Array.from({length:31},()=>PlanDesigner.step('Rast'))})",ctx),false);
  assert.equal(vm.runInContext('pd.draft.steps.length',ctx),29);
  vm.runInContext("pd.draft=PlanDesigner.create();pd.dockTab='temporary';pd.selected=null;pd.selection=[];pdInsert({},'dock');pdInsert({},'dock');pdSelectStep(pd.draft.dock[0].id,'dock');pdSelectStep(pd.draft.dock[1].id,'dock',{shiftKey:true});pdRender()",ctx);
  await vm.runInContext('pd.dockWrite',ctx);assert.equal(persistedDock.length,0);
  const dropSelected=zone=>{const ids=JSON.parse(vm.runInContext('JSON.stringify(pdSelectedIds())',ctx));zone.events.drop({preventDefault(){},stopPropagation(){},dataTransfer:{getData(){return JSON.stringify({id:ids[0],ids});}}});};
  assert.equal(nodes.designerDockTools.children.some(b=>b.title==='Dauerhaft speichern'),false);
  dropSelected(nodes.designerDockTabs.children[1]);
  await vm.runInContext('pd.dockWrite',ctx);assert.equal(persistedDock.length,2);
  assert.equal(nodes.designerDock.children.length,2);
  await nodes.designerDock.children[0].children.at(-1).click();
  await vm.runInContext('pd.dockWrite',ctx);assert.equal(persistedDock.length,1);
  nodes.designerDock.children[0].click();
  dropSelected(nodes.designerDockTabs.children[0]);
  await vm.runInContext('pd.dockWrite',ctx);assert.equal(persistedDock.length,0);
  assert.equal(vm.runInContext('pd.draft.dock.length',ctx),3);
  vm.runInContext('pd.draft.dock=[];pd.dockReady=null',ctx);await vm.runInContext('pdLoadDock()',ctx);
  assert.equal(vm.runInContext('pd.draft.dock.length',ctx),0);
  vm.runInContext("pd.draft=PlanDesigner.create();pd.draft.steps=[PlanDesigner.step('A'),PlanDesigner.step('B')];pd.dockTab='saved';pdSelectStep(pd.draft.steps[0].id,'steps');pdSelectStep(pd.draft.steps[1].id,'steps',{shiftKey:true});pdRender()",ctx);
  dropSelected(nodes.designerDock);
  await vm.runInContext('pd.dockWrite',ctx);
  assert.equal(persistedDock.length,2);assert.equal(nodes.designerDock.children.length,2);
  assert.equal(vm.runInContext('pd.draft.steps.length',ctx),2);
  vm.runInContext('pdHistory("undo","redo")',ctx);await vm.runInContext('pd.dockWrite',ctx);
  assert.equal(persistedDock.length,0);assert.equal(vm.runInContext('pd.draft.steps.length',ctx),2);
  vm.runInContext('pdHistory("redo","undo")',ctx);await vm.runInContext('pd.dockWrite',ctx);assert.equal(persistedDock.length,2);
  vm.runInContext('pd.draft.dock=[];pd.dockReady=null',ctx);await vm.runInContext('pdLoadDock()',ctx);assert.equal(nodes.designerDock.children.length,2);
  assert.equal(nodes.designerDockTabs.children[0].textContent,'Ablage');
  vm.runInContext("pdSelectStep(pd.draft.dock[1].id,'dock');pdRender()",ctx);
  const lastSavedId=vm.runInContext('pd.selected',ctx);
  dropSelected(nodes.designerDock.children[0]);
  assert.equal(vm.runInContext('pd.draft.dock.length',ctx),2);
  assert.equal(vm.runInContext('pd.draft.dock[0].id',ctx),lastSavedId);
  nodes.designerDockTabs.children[0].click();
  vm.runInContext("pdSelectStep(pd.draft.steps[0].id,'steps');pdRender()",ctx);
  dropSelected(nodes.designerDock);
  assert.equal(vm.runInContext('pd.draft.steps.length',ctx),1);
  assert.equal(nodes.designerDock.children.length,1);
  await vm.runInContext('pd.dockWrite',ctx);assert.equal(persistedDock.length,2);
  for(const tab of ['temporary','saved']){
    ctx.testDockTab=tab;
    vm.runInContext("pd.draft=PlanDesigner.create();pd.dockTab=testDockTab;pd.draft.dock=['A','B','C','D'].map(name=>({...PlanDesigner.step(name),dockSaved:testDockTab==='saved'}));pdSelectStep(pd.draft.dock[0].id,'dock');pdSelectStep(pd.draft.dock[1].id,'dock',{shiftKey:true});pdRender()",ctx);
    const row=nodes.designerDock.children[3];row.getBoundingClientRect=()=>({top:100,height:40});
    const ids=JSON.parse(vm.runInContext('JSON.stringify(pdSelectedIds())',ctx));
    row.events.drop({clientY:135,preventDefault(){},stopPropagation(){},dataTransfer:{getData(){return JSON.stringify({id:ids[0],ids});}}});
    assert.equal(vm.runInContext('pdDockItems().map(s=>s.Rast).join()',ctx),'C,D,A,B');
    assert.equal(vm.runInContext('pd.draft.dock.length',ctx),4);
    await vm.runInContext('pd.dockWrite',ctx);
    assert.equal(persistedDock.map(s=>s.Rast).join(),tab==='saved'?'C,D,A,B':'');
  }
  vm.runInContext("pd.draft=PlanDesigner.create();pd.draft.steps=[PlanDesigner.step('Abmaischen'),PlanDesigner.step('Kochen')];pd.comparison=PlanDesigner.create();pd.comparison.steps=[PlanDesigner.step('Abmaischen'),PlanDesigner.step('RHE:100'),PlanDesigner.step('RHE:25'),PlanDesigner.step('Kochen'),PlanDesigner.step('Ende')];pdRender()",ctx);
  const comparisonBody=()=>nodes.designerComparison.children[0].children[0].children[1];
  comparisonBody().children[1].children[1].children[0].click();
  assert.equal(vm.runInContext('pd.draft.steps.map(s=>s.Rast).join()',ctx),'Abmaischen,RHE:100,Kochen');
  comparisonBody().children[2].children[1].children[0].click();
  assert.equal(vm.runInContext('pd.draft.steps.map(s=>s.Rast).join()',ctx),'Abmaischen,RHE:100,RHE:25,Kochen');
  comparisonBody().children.at(-1).children[1].children[0].click();
  assert.equal(vm.runInContext('pd.draft.steps.at(-1).Rast',ctx),'Ende');
  vm.runInContext('pdHistory("undo","redo")',ctx);
  assert.equal(vm.runInContext('pd.draft.steps.at(-1).Rast',ctx),'Kochen');
  vm.runInContext("pd.draft=PlanDesigner.create();pd.draft.steps=[PlanDesigner.step('RHE: 100')];pd.dockTab='saved';pdSelectStep(pd.draft.steps[0].id,'steps');pdRender()",ctx);
  dropSelected(nodes.designerDock);await vm.runInContext('pd.dockWrite',ctx);
  assert.equal(persistedDock[0].Rast,'RHE:100');
  assert.equal(nodes.designerDock.children[0].children[1].textContent,'RHE:100');
  vm.runInContext("pd.draft=PlanDesigner.create();pd.draft.snapshot={actors:[{NAME:'Ruehrwerk',PWMSW:1}],kettles:[]};pd.draft.steps=[PlanDesigner.step('Ruehrwerk:OFF:Läuterpause')];pdSelectStep(pd.draft.steps[0].id,'steps');pdRender()",ctx);
  assert.equal(nodes.designerActorAction.value,'OFF');
  assert.equal(vm.runInContext("PlanDesigner.review(pd.draft).some(n=>n.code==='actor_argument'||n.code==='resource_unknown')",ctx),false);
  nodes.designerActorAction.value='ON';nodes.designerActorAction.events.change();
  assert.equal(vm.runInContext('pd.draft.steps[0].Rast',ctx),'Ruehrwerk:ON:Läuterpause');
  nodes.designerActorAction.value='PWM';nodes.designerActorAction.events.change();
  nodes.designerActorPower.value='50';nodes.designerActorPower.events.change();
  assert.equal(vm.runInContext('pd.draft.steps[0].Rast',ctx),'Ruehrwerk:50:Läuterpause');
  assert.equal(vm.runInContext("PlanDesigner.commandAction(PlanDesigner.step('worker/Ruehrwerk:OFF:Läuterpause'),null)",ctx),null);
  ctx.document.activeElement=null;
  vm.runInContext("pd.draft=PlanDesigner.create();pd.draft.name='Update regression';pd.draft.steps=[PlanDesigner.step('Ruehrwerk:OFF')];pdSelectStep(pd.draft.steps[0].id,'steps');pdRender()",ctx);
  await vm.runInContext('pdSave()',ctx);
  const updateId=vm.runInContext('pd.draft.id',ctx);
  const pendingName=nodes.designerProperties.children.find(n=>n.textContent==='Schritt').children[0];
  pendingName.value='Ruehrwerk:OFF:Läuterpause';pendingName.tagName='INPUT';pendingName.form=nodes.designerProperties;
  pendingName.dispatchEvent=event=>pendingName.events[event.type]();
  nodes.designerProperties.events.input({target:pendingName});
  await vm.runInContext('pdSaveChoice()',ctx);
  await nodes.designerDialog.children[1].children[0].click();
  assert.equal(saved.get(updateId).steps[0].Rast,'Ruehrwerk:OFF:Läuterpause');
  assert.equal(vm.runInContext('pd.draft.id',ctx),updateId);
  assert.equal(vm.runInContext('pd.draft.version',ctx),1);
  const iconCss=fs.readFileSync('static/icomoon/style.css','utf8')+fs.readFileSync('static/styles.css','utf8');
  for(const node of elements.filter(e=>e.className.startsWith('icon-')))assert.ok(iconCss.includes('.'+node.className.split(' ')[0]+':'),node.className+' must exist');
  console.log('Designer UI: initialization, masked credentials, DnD dock, undo/redo, save, discard guard and toolbar actions verified');
})().catch(error=>{console.error(error);process.exitCode=1;});
